# Generated by Django 4.2.6 on 2023-10-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Место')),
                ('time', models.TimeField(auto_now_add=True, null=True, verbose_name='Время')),
                ('action', models.CharField(blank=True, max_length=200, null=True, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак приятной привычки')),
                ('frequency', models.IntegerField(blank=True, default=1, null=True, verbose_name='Периодичность в днях')),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вознаграждение')),
                ('duration', models.IntegerField(blank=True, default=5, null=True, verbose_name='Время на выполнение в минутах')),
                ('public', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак публичности')),
                ('connected_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
