# Generated by Django 4.2.6 on 2023-10-30 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='next_reminder_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата последнего напоминания'),
        ),
        migrations.AddField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='Время на выполнение в минутах'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(blank=True, default='12:00', null=True, verbose_name='Время'),
        ),
    ]
