# Generated by Django 4.2.6 on 2023-10-28 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_habit_last_reminder_date_habit_user_alter_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='last_reminder_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата последнего напоминания'),
        ),
    ]
