# Generated by Django 4.2.6 on 2023-10-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_habit_last_reminder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='Время на выполнение в минутах'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(blank=True, default='12:00', null=True, verbose_name='Время'),
        ),
    ]
